name: Run Unit Tests for Snowflake Python SP

on:
  push:
    paths:
      - 'DEV/sp/**.py'
      - 'DEV/tests/**.py'
  pull_request:
    paths:
      - 'DEV/sp/**.py'
      - 'DEV/tests/**.py'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install pytest 
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Run Pytest and generate report
        run: |
          pytest DEV/tests/ --junitxml=test-results.xml

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: test-results.xml

      - name: Continue to next step if tests pass
        if: ${{ success() }}
        run: echo "Tests passed! Proceeding to next steps..."
